// flow-typed signature: fc5042c629d7df870672154ae8a72258
// flow-typed version: <<STUB>>/styled-tools_v0.6.0/flow_v0.82.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'styled-tools'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

type pass = string | number;

type fail = any;

type test = string | Function | null;

type needle = string | Function;

type switches = Object;

declare module "styled-tools" {
  declare export function switchProp(test: needle, switches: switches): Function;
  declare export function ifProp(test: test, pass, fail?: fail): Function;
}